export const ambientTheme = {
  accent: '#3e82ff',
  accent35: 'rgba(62, 130, 255, 0.35)',
  accent2: 'rgba(62, 130, 255, 0.2)',
  border: '#162123',
  foreground: 'white',
  'background-primary': '#131d1e',
  'background-secondary': '#162123',
  'border-color-base': 'var(--text-color)',
  'border-color-split': '#1C2E2F',
  'text-color': '#4e5d6a',
  'text-color-secondary': 'rgba(78, 93, 106, 0.65)',
  'text-color-inverse': '#fff',
  'text-color-inverse-fade': 'rgba(0, 0, 0, 0.5)',
  'icon-color': 'var(--text-color)',
  'icon-color-hover': 'rgba(78, 93, 106, 0.75)',
  'heading-color': 'rgba(255, 255, 255, 0.85)',
  'disabled-color': 'rgba(78, 93, 106, 0.5)',
  'background-color-light': 'var(--background-primary)',
  'background-color-base': 'var(--background-secondary)',
  'disabled-bg': 'var(--background-color-base)',
  'disabled-color-dark': 'rgba(255, 255, 255, 0.35)',
  'radio-disabled-button-checked-bg': '#e6e6e6',
  'radio-dot-disabled-color': 'rgba(78, 93, 106, 0.2)',
  'input-icon-hover-color': 'rgba(0, 0, 0, 0.85)',
  'modal-mask-bg': 'rgba(78, 93, 106, 0.45)',
  'switch-shadow-color': 'rgba(0, 35, 11, 0.2)',
  'steps-nav-arrow-color': 'rgba(255, 255, 255, 0.25)',
  'shade-40-text-color-secondary': 'rgba(0, 0, 0, 0.67)',
  'picker-cell-color': 'rgba(78, 93, 106, 0.45)',
  'picker-bg': 'var(--background-secondary)',
  'picker-panel-bg': 'var(--background-secondary)',
  'picker-basic-cell-active-with-range-color': '#969ad8',
  'picker-basic-cell-hover-with-range-color': '#7176ca',
  'picker-header-button': 'var(--text-color)',
  'picker-header-button-main': 'var(--heading-color)',
  'menu-item-active-bg': 'var(--background-secondary)',
  'modal-content-bg': 'var(--background-secondary)',
  'message-notice-content-bg': 'var(--background-secondary)',
  'message-text-color': 'var(--heading-color)',
  'notification-bg': 'var(--background-secondary)',
  'popover-background': 'var(--background-secondary)',
  'drawer-bg': 'var(--background-secondary)',
  'tooltip-bg': 'var(--text-color)',
  'tooltip-color': 'var(--heading-color)',
  'scroll-thumb-color': 'var(--text-color)',
  'scroll-bg': 'var(--background-primary)',
  'btn-default-color': 'var(--heading-color)',
  'process-tail-color': 'var(--border-color-base)',
  'skeleton-color': 'var(--text-color)',
  'skeleton-to-color': '#121c1d',
  'divider-color': 'rgba(255, 255, 255, 0.06)',
  'checkbox-color': 'var(--accent)',
  'input-number-handler-border-color': 'var(--text-color)',
  'sbmenu-border': 'var(--background-secondary)',
  'draggable-background-1': 'var(--background-primary)',
  'draggable-background-2': 'var(--background-secondary)'
};

export const defaultTheme = {
  'accent': '#3E82FF',
  'accent35': 'rgba(62, 130, 255, 0.35)',
  'accent2': 'rgba(62, 130, 255, 0.2)',
  'border': '#f0f0f0',
  'foreground': 'white',
  'background-primary': '#ffffff',
  'background-secondary': '#f7f8fa',
  'border-color-base': '#d9d9d9',
  'border-color-split': '#f0f0f0',
  'picker-cell-color': 'rgba(0, 0, 0, 0.25)',
  'picker-bg': 'var(--background-primary)',
  'picker-basic-cell-active-with-range-color': '#f5f0ff',
  'picker-basic-cell-hover-with-range-color': '#ffffff',
  'picker-panel-bg': 'var(--background-primary)',
  'picker-header-button': 'rgba(0, 0, 0, 0.25)',
  'picker-header-button-main': 'var(--text-color)',
  'disabled-color': 'rgba(0, 0, 0, 0.25)',
  'item-hover-bg': '#f5f5f5',
  'text-color': 'rgba(0, 0, 0, 0.65)',
  'text-color-secondary': 'rgba(0, 0, 0, 0.45)',
  'text-color-inverse': '#fff',
  'text-color-inverse-fade': 'rgba(255, 255, 255, 0.5)',
  'icon-color': 'inherit',
  'icon-color-hover': 'rgba(0, 0, 0, 0.75)',
  'heading-color': 'rgba(0, 0, 0, 0.85)',
  'menu-item-active-bg': '#f5f0ff',
  'message-text-color': 'var(--text-color)',
  'notification-bg': 'var(--background-primary)',
  'popover-background': 'var(--background-primary)',
  'drawer-bg': 'var(--background-primary)',
  'tooltip-bg': 'rgba(0, 0, 0, 0.75)',
  'tooltip-color': '#fff',
  'process-tail-color': 'var(--border-color-split)',
  'background-color-light': 'var(--background-primary)',
  'background-color-base': 'var(--background-secondary)',
  'disabled-bg': 'var(--background-color-base)',
  'disabled-color-dark': 'rgba(255, 255, 255, 0.35)',
  'radio-disabled-button-checked-bg': '#e6e6e6',
  'radio-dot-disabled-color': 'rgba(0, 0, 0, 0.2)',
  'input-icon-hover-color': 'rgba(0, 0, 0, 0.85)',
  'modal-mask-bg': 'rgba(0, 0, 0, 0.45)',
  'modal-content-bg': 'var(--background-primary)',
  'switch-shadow-color': 'rgba(0, 35, 11, 0.2)',
  'message-notice-content-bg': 'var(--background-primary)',
  'steps-nav-arrow-color': 'rgba(0, 0, 0, 0.25)',
  'shade-40-text-color-secondary': 'rgba(0, 0, 0, 0.67)',
  'scroll-thumb-color': '#999',
  'scroll-bg': '#fff',
  'btn-default-color': 'var(--text-color)',
  'skeleton-color': '#f2f2f2',
  'divider-color': 'rgba(0, 0, 0, 0.06)',
  'checkbox-color': 'var(--accent)',
  'input-number-handler-border-color': 'var(--border-color-base)',
  'sbmenu-border': 'var(--border)',
  'draggable-background-1': 'var(--background-secondary)',
  'draggable-background-2': 'var(--background-primary)'
};